spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APIKEY}
    properties:
      mail:
      smtp:
       auth: true
       starttls.enable: true
       starttls.required: true
       emails.sender_email: ${EMAIL_TEST}
  devtools:
    restart:
      enabled: false
server:
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG